### ISSUE TITLE
text-align: center 和 margin: 0 auto 的区别 | Qcmoke's Blog

### ISSUE THREAD

**Issue by qcmoke** [qcmoke/gitalk#133]
http://localhost:4000/front/text_align_and_margin_0_auto.html

**Comment by qcmoke** [comment]
```java
public void main(){
}
```

**Comment by qcmoke** [comment]
```css
div{
 top: 13px;
}
```

**Comment by qcmoke** [comment]
```java
package com.qcmoke.auth;

import com.qcmoke.common.annotation.EnableAutoRedisService;
import com.qcmoke.common.annotation.EnableAutoResourceServerSecurity;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;


/**
 * @author qcmoke
 */
@EnableAutoResourceServerSecurity
@EnableAutoRedisService
@EnableDiscoveryClient
@MapperScan("com.qcmoke.auth.mapper")
@SpringBootApplication
public class AuthServerApplication {
    public static void main(String[] args) {
        SpringApplication.run(AuthServerApplication.class, args);
    }
}


```

**Comment by qcmoke** [comment]
lala

**Comment by qcmoke** [comment]
@
```css
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <style type="text/css">
        .div1{
            width: 400px;
            height: 400px;
            background-color: skyblue;
            margin: 0 auto;
        }
    </style>
</head>
<body>
    <div class="div1">
        我是文字
    </div>
</body>
</html>
```
